//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.04 at 09:42:03 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/course-details", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.course_details;
